### We created a package in the form of text_encoder.pt


```text
text_encoder.pt
│
├── model_state
│   │
│   ├── embedding.weight
│   ├── projection.weight
│   └── projection.bias
│
├── vocab
│
├── embedding_dim = 32
│
├── output_dim = 16
│
└── initial_embeddings
```

In [1]:
from pathlib import Path

model_path = Path("../models/text_encoder.pt")

print("File exists:", model_path.exists())
print("Full path:", model_path.resolve())

File exists: True
Full path: /Users/sushilpratapsingh/projects/mini-neural-search/models/text_encoder.pt

In [2]:
import torch

checkpoint = torch.load(
    "../models/text_encoder.pt",
    map_location="cpu",
    weights_only=True
)

print("Loaded object type:", type(checkpoint))
print(checkpoint.keys())

Loaded object type: <class 'dict'>
dict_keys(['model_state', 'vocab', 'embedding_dim', 'output_dim', 'initial_embeddings'])

In [49]:


checkpoint = torch.load(
    "../models/text_encoder.pt",
    map_location="cpu",
    weights_only=True
)

state = checkpoint["model_state"]

print("model state: ", checkpoint["model_state"])
print("Vocabulary size:", len(checkpoint["vocab"]))
print("Embedding dimensions:", checkpoint["embedding_dim"])
print("Output dimensions:", checkpoint["output_dim"])

print("\nSaved model parameters:")
for name, tensor in state.items():
    print(f"{name:30s} Shape: {tuple(tensor.shape)}")

model state:  OrderedDict([('embedding.weight', tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-1.3847, -0.8712, -0.2234,  ...,  1.8446, -1.1845,  1.3835],
        [ 1.4122,  0.7336,  2.2255,  ..., -0.7492,  1.3516,  0.5532],
        ...,
        [-0.5463, -0.6607,  0.2517,  ..., -0.4410,  1.0555, -1.3477],
        [ 0.4723, -0.0795, -0.1661,  ..., -1.1575,  0.0462, -0.3146],
        [ 0.8535, -0.0585,  0.7543,  ...,  0.3706,  0.1984,  0.2184]])), ('projection.weight', tensor([[-0.0552, -0.1632,  0.1316,  0.1599,  0.0228,  0.0572, -0.0741,  0.0343,
         -0.2087,  0.1684, -0.0107, -0.2050,  0.1009, -0.0136, -0.2326, -0.0737,
         -0.0714,  0.0325,  0.0505, -0.0368, -0.1888,  0.2165, -0.0943,  0.0482,
          0.0449,  0.0817, -0.0178, -0.0829,  0.1042, -0.1499, -0.1352,  0.0066],
        [ 0.0167, -0.0347, -0.0231,  0.0036, -0.0364,  0.1691, -0.0333, -0.0677,
          0.1148,  0.2576,  0.0576, -0.0457, -0.2007,  0.0229,  0.1947, -0.1820,
          0.1757, -0.1761,  0.0230,  0.1790, -0.0340, -0.1867,  0.0826,  0.1564,
          0.0387,  0.0007,  0.1801,  0.0262, -0.1512,  0.0419,  0.0481, -0.1945],
        [ 0.0011, -0.2030, -0.1738,  0.1162, -0.2076,  0.0070,  0.0143,  0.1715,
         -0.1558, -0.2107,  0.1089,  0.1431,  0.2991,  0.0584, -0.0261,  0.1446,
         -0.0751, -0.0377, -0.1859,  0.1614,  0.1516,  0.2900, -0.2976, -0.0748,
         -0.1356, -0.0418,  0.0138, -0.1877,  0.1668,  0.0147, -0.1023, -0.0525],
        [ 0.0387,  0.1040, -0.1262, -0.2027, -0.0352,  0.1751,  0.0814,  0.0171,
         -0.0104,  0.0571, -0.1380, -0.2527, -0.0496, -0.0637, -0.0629,  0.1906,
         -0.0804,  0.0751, -0.0110, -0.0514, -0.1250,  0.0834,  0.1919,  0.1166,
         -0.0339,  0.1130, -0.2541, -0.0101,  0.1109, -0.1112, -0.2209, -0.2172],
        [ 0.1441,  0.0611, -0.1823,  0.0719,  0.0337, -0.0017,  0.0108, -0.0392,
          0.0857,  0.1332,  0.0040,  0.0157, -0.2445,  0.0282, -0.0459, -0.0571,
          0.0722, -0.0790,  0.1498,  0.1047, -0.0125, -0.1804,  0.0598,  0.0303,
          0.1160,  0.2317,  0.0736,  0.1404,  0.1178, -0.0434, -0.1559,  0.0246],
        [ 0.1139, -0.0646,  0.0762,  0.1245, -0.1243, -0.2288,  0.0014, -0.0271,
         -0.0636,  0.0262,  0.2833, -0.2336,  0.1224, -0.0779, -0.1356,  0.1822,
         -0.1283,  0.0882,  0.0040,  0.2712, -0.0099,  0.0053,  0.2382, -0.0449,
          0.0239,  0.0596, -0.1608, -0.0064, -0.0148,  0.2776, -0.1583,  0.0620],
        [ 0.1805, -0.1689,  0.2457,  0.2497,  0.0077, -0.2740,  0.1445,  0.0591,
         -0.0216, -0.2222,  0.1804,  0.0274, -0.1648, -0.0535,  0.0120, -0.1597,
          0.0435, -0.0470, -0.0198, -0.0931, -0.1348, -0.1711, -0.0027,  0.2330,
         -0.2274,  0.1786, -0.1826,  0.0320,  0.0706, -0.0115,  0.0511, -0.1135],
        [-0.1481,  0.0114,  0.0649,  0.1230, -0.2653,  0.0802,  0.0902,  0.3036,
          0.1024, -0.1756,  0.1891,  0.0793, -0.1980,  0.0525, -0.0057,  0.2926,
          0.2092,  0.0830, -0.1305, -0.1554, -0.1580,  0.0232,  0.0020, -0.0055,
         -0.1457, -0.2251, -0.1090,  0.0885, -0.0513,  0.1800,  0.0577, -0.0559],
        [ 0.0467,  0.0338, -0.0838,  0.0541,  0.1429,  0.2236, -0.0581,  0.0237,
         -0.1991, -0.1162, -0.1327,  0.1109,  0.2536, -0.0383, -0.1858, -0.1809,
          0.0390,  0.0362,  0.1619, -0.1918, -0.1906,  0.1805, -0.1470, -0.0210,
          0.0263, -0.0628, -0.1633, -0.1608,  0.0326, -0.1753,  0.1104, -0.0862],
        [-0.0133, -0.1468,  0.1697,  0.1386, -0.0526,  0.2422, -0.2765,  0.1677,
          0.0249,  0.0430, -0.2386, -0.1767, -0.1307,  0.1286, -0.1820,  0.0665,
         -0.1833,  0.0645,  0.1053,  0.2288, -0.1378,  0.2230,  0.1020,  0.1435,
         -0.0162,  0.1385, -0.1337,  0.0480,  0.1652,  0.0113, -0.0868,  0.1798],
        [-0.0701, -0.0131, -0.0893, -0.2673,  0.0372, -0.1795,  0.1194, -0.2211,
         -0.1830, -0.1083, -0.2360,  0.0911,  0.0985, -0.0044,  0.1721, -0.0637,
          0.0225, -0.0429,  0.0080, -0.1917,  0.1575, -0.0011, -0.0308, -0.0036,
          0.1589, -0.0023, -0.1174, -0.1055, -0.0745,  0.0520,  0.0368, -0.0810],
        [ 0.0506, -0.2062,  0.2345, -0.0277,  0.0572, -0.0911,  0.0913,  0.0059,
          0.1241, -0.2054,  0.0044,  0.1275, -0.0781,  0.0870,  0.2356, -0.1776,
         -0.0032,  0.0109,  0.0139, -0.2324, -0.2030, -0.2159,  0.2791,  0.1308,
         -0.0323, -0.0467, -0.2237,  0.0154,  0.0809, -0.1618,  0.0508, -0.1847],
        [ 0.0385, -0.0159,  0.2529, -0.0562, -0.1476,  0.0710, -0.0324, -0.0989,
          0.0558,  0.0687, -0.0552, -0.0420, -0.2196,  0.0239,  0.0186,  0.0322,
          0.0083,  0.0418,  0.0405, -0.1292,  0.0545, -0.1631,  0.0600,  0.2370,
         -0.2720, -0.1255,  0.0058, -0.0207, -0.1190,  0.0105,  0.0734,  0.1231],
        [ 0.0927, -0.1182,  0.1100,  0.1280,  0.1148,  0.0522,  0.1576,  0.0873,
          0.0173, -0.1991,  0.1786, -0.0465,  0.0423, -0.0318, -0.0090, -0.0131,
          0.0427, -0.0239, -0.0569,  0.2622, -0.2499, -0.2186,  0.0255, -0.1227,
         -0.0548,  0.0036, -0.0997,  0.0306,  0.0738,  0.0469, -0.0206, -0.1361],
        [ 0.0851, -0.2967,  0.2797, -0.0886,  0.1074, -0.2472,  0.0116, -0.2632,
         -0.0528,  0.1977,  0.1380,  0.0195,  0.2668, -0.0095, -0.0116,  0.0541,
         -0.1573, -0.1475, -0.2567,  0.0883,  0.1870,  0.2433,  0.0979, -0.1323,
         -0.0924, -0.1466,  0.1300, -0.1223,  0.0356, -0.1237, -0.1610, -0.0164],
        [ 0.0535,  0.0225, -0.1885, -0.0340, -0.0572,  0.1644,  0.0026,  0.2347,
          0.2573, -0.1945, -0.1383,  0.0543, -0.0888,  0.0171,  0.0314,  0.0796,
          0.0420,  0.0716,  0.0500, -0.0352, -0.2739,  0.1464, -0.3360, -0.1214,
          0.2479, -0.0281,  0.0644, -0.0446,  0.0756, -0.0663,  0.0618, -0.0818]])), ('projection.bias', tensor([ 0.0465, -0.0413, -0.1034, -0.0281,  0.1396, -0.0333,  0.0730, -0.0866,
        -0.0310, -0.0338, -0.1555,  0.0619, -0.1192,  0.0181, -0.1588,  0.0969]))])
Vocabulary size: 93
Embedding dimensions: 32
Output dimensions: 16

Saved model parameters:
embedding.weight               Shape: (93, 32)
projection.weight              Shape: (16, 32)
projection.bias                Shape: (16,)

In [ ]:


checkpoint = torch.load(
    "../models/text_encoder.pt",
    map_location="cpu",
    weights_only=True
)

vocab = checkpoint["vocab"]

print("Vocabulary size:", len(vocab))
print(vocab)

Vocabulary size: 93
{'<PAD>': 0, '<UNK>': 1, 'a': 2, 'about': 3, 'access': 4, 'an': 5, 'and': 6, 'api': 7, 'apis': 8, 'application': 9, 'applications': 10, 'authentication': 11, 'aws': 12, 'backpropagation': 13, 'boot': 14, 'build': 15, 'cache': 16, 'caching': 17, 'cloud': 18, 'containers': 19, 'database': 20, 'deploy': 21, 'descent': 22, 'distributed': 23, 'do': 24, 'docker': 25, 'document': 26, 'does': 27, 'embeddings': 28, 'engine': 29, 'faster': 30, 'find': 31, 'for': 32, 'gradient': 33, 'how': 34, 'i': 35, 'improve': 36, 'in': 37, 'indexes': 38, 'java': 39, 'learn': 40, 'learning': 41, 'logs': 42, 'machine': 43, 'make': 44, 'metrics': 45, 'microservices': 46, 'model': 47, 'monitor': 48, 'my': 49, 'network': 50, 'neural': 51, 'oauth': 52, 'observe': 53, 'on': 54, 'optimize': 55, 'package': 56, 'performance': 57, 'protect': 58, 'queries': 59, 'query': 60, 'reduce': 61, 'response': 62, 'rest': 63, 'retrieval': 64, 'run': 65, 'search': 66, 'secure': 67, 'security': 68, 'semantic': 69, 'services': 70, 'similar': 71, 'software': 72, 'speed': 73, 'spring': 74, 'sql': 75, 'store': 76, 'text': 77, 'the': 78, 'time': 79, 'to': 80, 'tokens': 81, 'traces': 82, 'tracing': 83, 'train': 84, 'training': 85, 'up': 86, 'use': 87, 'using': 88, 'vector': 89, 'vectors': 90, 'with': 91, 'work': 92}

In [10]:
print("First 20 vocabulary entries:\n")

for token, token_id in list(vocab.items())[:20]:
    print(f"{token:20s} -> {token_id}")

print("\nPossible special tokens:")

for token, token_id in vocab.items():
    if (
        "unk" in token.lower()
        or "pad" in token.lower()
        or "bos" in token.lower()
        or "eos" in token.lower()
    ):
        print(f"{token:20s} -> {token_id}")

First 20 vocabulary entries:

<PAD>                -> 0
<UNK>                -> 1
a                    -> 2
about                -> 3
access               -> 4
an                   -> 5
and                  -> 6
api                  -> 7
apis                 -> 8
application          -> 9
applications         -> 10
authentication       -> 11
aws                  -> 12
backpropagation      -> 13
boot                 -> 14
build                -> 15
cache                -> 16
caching              -> 17
cloud                -> 18
containers           -> 19

Possible special tokens:
<PAD>                -> 0
<UNK>                -> 1

In [12]:
import json

with open("../data/training_pairs.json", "r") as f:
    training_data = json.load(f)

print("Type:", type(training_data))
print("Number of examples:", len(training_data))

print("\nFIRST REAL TRAINING EXAMPLE:")
print(training_data)

Type: <class 'dict'>
Number of examples: 2

FIRST REAL TRAINING EXAMPLE:
{'documents': [{'id': 'd1', 'text': 'Deploy a Spring Boot application to AWS using containers'}, {'id': 'd2', 'text': 'Train a neural network using backpropagation and gradient descent'}, {'id': 'd3', 'text': 'Store text embeddings in a vector database for semantic search'}, {'id': 'd4', 'text': 'Improve application response time using caching'}, {'id': 'd5', 'text': 'Secure REST APIs using OAuth and access tokens'}, {'id': 'd6', 'text': 'Monitor microservices with logs metrics and distributed tracing'}, {'id': 'd7', 'text': 'Use Docker containers to package and deploy applications'}, {'id': 'd8', 'text': 'Optimize database queries using indexes'}], 'training_pairs': [{'query': 'how do I train a machine learning model', 'document_id': 'd2'}, {'query': 'learn about neural network training', 'document_id': 'd2'}, {'query': 'how does backpropagation work', 'document_id': 'd2'}, {'query': 'find similar text using embeddings', 'document_id': 'd3'}, {'query': 'build a semantic document search engine', 'document_id': 'd3'}, {'query': 'store vectors for text retrieval', 'document_id': 'd3'}, {'query': 'deploy a Java application on AWS', 'document_id': 'd1'}, {'query': 'run Spring Boot in the cloud', 'document_id': 'd1'}, {'query': 'deploy software using Docker', 'document_id': 'd7'}, {'query': 'package applications in containers', 'document_id': 'd7'}, {'query': 'make my application faster with a cache', 'document_id': 'd4'}, {'query': 'reduce API response time', 'document_id': 'd4'}, {'query': 'protect an API with authentication', 'document_id': 'd5'}, {'query': 'use OAuth tokens for API security', 'document_id': 'd5'}, {'query': 'monitor services using logs and traces', 'document_id': 'd6'}, {'query': 'observe distributed microservices', 'document_id': 'd6'}, {'query': 'speed up SQL queries with indexes', 'document_id': 'd8'}, {'query': 'improve database query performance', 'document_id': 'd8'}]}

### Display the entire trained matrix with token alongside

In [13]:
checkpoint
state
vocab

{'<PAD>': 0,
 '<UNK>': 1,
 'a': 2,
 'about': 3,
 'access': 4,
 'an': 5,
 'and': 6,
 'api': 7,
 'apis': 8,
 'application': 9,
 'applications': 10,
 'authentication': 11,
 'aws': 12,
 'backpropagation': 13,
 'boot': 14,
 'build': 15,
 'cache': 16,
 'caching': 17,
 'cloud': 18,
 'containers': 19,
 'database': 20,
 'deploy': 21,
 'descent': 22,
 'distributed': 23,
 'do': 24,
 'docker': 25,
 'document': 26,
 'does': 27,
 'embeddings': 28,
 'engine': 29,
 'faster': 30,
 'find': 31,
 'for': 32,
 'gradient': 33,
 'how': 34,
 'i': 35,
 'improve': 36,
 'in': 37,
 'indexes': 38,
 'java': 39,
 'learn': 40,
 'learning': 41,
 'logs': 42,
 'machine': 43,
 'make': 44,
 'metrics': 45,
 'microservices': 46,
 'model': 47,
 'monitor': 48,
 'my': 49,
 'network': 50,
 'neural': 51,
 'oauth': 52,
 'observe': 53,
 'on': 54,
 'optimize': 55,
 'package': 56,
 'performance': 57,
 'protect': 58,
 'queries': 59,
 'query': 60,
 'reduce': 61,
 'response': 62,
 'rest': 63,
 'retrieval': 64,
 'run': 65,
 'search': 66,
 'secure': 67,
 'security': 68,
 'semantic': 69,
 'services': 70,
 'similar': 71,
 'software': 72,
 'speed': 73,
 'spring': 74,
 'sql': 75,
 'store': 76,
 'text': 77,
 'the': 78,
 'time': 79,
 'to': 80,
 'tokens': 81,
 'traces': 82,
 'tracing': 83,
 'train': 84,
 'training': 85,
 'up': 86,
 'use': 87,
 'using': 88,
 'vector': 89,
 'vectors': 90,
 'with': 91,
 'work': 92}

In [14]:
import pandas as pd

embedding_weights = state["embedding.weight"]

# Create ID -> token mapping
id_to_token = {
    token_id: token
    for token, token_id in vocab.items()
}

rows = []

for token_id in range(embedding_weights.shape[0]):
    vector = embedding_weights[token_id].detach().cpu().numpy()

    row = {
        "token_id": token_id,
        "token": id_to_token.get(token_id, "<UNKNOWN>")
    }

    for dimension, value in enumerate(vector):
        row[f"dim_{dimension}"] = value

    rows.append(row)

embedding_df = pd.DataFrame(rows)

display(embedding_df)

,token_id,token,dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,...,dim_22,dim_23,dim_24,dim_25,dim_26,dim_27,dim_28,dim_29,dim_30,dim_31
0,0,<PAD>,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,<UNK>,-1.384674,-0.871236,-0.223366,1.717361,0.318880,-0.424519,0.305720,-0.774593,...,-0.814008,-0.735993,-1.403248,0.036004,-0.063477,0.675615,-0.097807,1.844594,-1.184537,1.383549
2,2,a,1.412244,0.733552,2.225478,0.646494,0.255072,0.021331,-0.927380,1.410813,...,0.974690,0.208253,0.651099,-0.583595,-0.982341,0.471626,-1.576418,-0.749228,1.351640,0.553172
3,3,about,-2.367893,0.347027,0.878709,0.159126,0.760469,0.431978,1.015781,-0.404073,...,-0.350886,0.615628,-0.094525,0.339779,0.053040,0.838260,1.103648,0.296956,0.803644,0.147983
4,4,access,1.779686,1.118745,-1.511048,-1.011624,-0.079041,1.808529,0.631201,0.708156,...,-0.848266,0.216666,0.451568,1.016571,-0.478962,1.538759,-2.392784,-0.346196,-1.070654,0.823736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,using,1.827057,-0.547246,-0.667803,-1.972026,1.422281,0.226328,0.102762,0.184316,...,0.295747,-0.312133,-0.064923,0.586813,-0.645650,-1.025219,-1.277812,0.412323,0.016059,-1.576406
89,89,vector,-0.861601,1.361308,0.262905,-1.278099,-0.612996,1.066388,1.561370,-1.376946,...,-1.238362,-2.209832,-0.464793,-1.639090,1.041190,-0.466126,-1.384426,-0.304102,0.959325,-1.027420
90,90,vectors,-0.546260,-0.660733,0.251661,-0.544274,-0.510380,-2.286444,-1.118766,-0.824566,...,-0.115498,-0.901091,0.389605,1.205763,1.400828,-1.184585,-1.214555,-0.440976,1.055473,-1.347707
91,91,with,0.472343,-0.079498,-0.166107,-0.090934,-0.167431,0.359207,-1.102688,0.176524,...,0.626040,0.858354,-1.054185,-1.353876,0.734810,0.869197,0.428037,-1.157533,0.046238,-0.314616
92,92,work,0.853466,-0.058474,0.754333,0.086567,0.245210,0.879219,-2.240332,-0.465927,...,1.131690,-0.122892,0.460051,0.642722,-1.666324,2.480873,0.470254,0.370639,0.198410,0.218439


### Also display the initial matrix

In [15]:
checkpoint["initial_embeddings"]

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-1.3847, -0.8712, -0.2234,  ...,  1.8446, -1.1845,  1.3835],
        [ 1.4451,  0.8564,  2.2181,  ..., -0.8278,  1.3347,  0.4835],
        ...,
        [ 0.0295, -0.5199, -0.1654,  ..., -0.3214,  0.5456, -1.2671],
        [ 0.5780, -0.0210, -0.1380,  ..., -1.0356,  0.1621, -0.3456],
        [ 0.7719,  0.0167,  0.6804,  ...,  0.5957,  0.2793,  0.2393]])

In [16]:
initial_embeddings = checkpoint["initial_embeddings"]

print("Initial:", initial_embeddings.shape)
print("Trained:", embedding_weights.shape)

Initial: torch.Size([93, 32])
Trained: torch.Size([93, 32])

# Now inspect one token, for example "neural" if it exists:

In [ ]:
word = "neural"

if word in vocab:
    token_id = vocab[word]

    print("Token:", word)
    print("Token ID:", token_id)

    print("\nBEFORE TRAINING:")
    print(initial_embeddings[token_id])

    print("\nAFTER TRAINING:")
    print(embedding_weights[token_id])

    print("\nCHANGE:")
    print(
        embedding_weights[token_id]
        - initial_embeddings[token_id]
    )
else:
    print(f"{word!r} is not in the vocabulary.")

Token: access
Token ID: 4

BEFORE TRAINING:
tensor([ 1.9312,  1.0119, -1.4364, -1.1299, -0.1360,  1.6354,  0.6547,  0.5760,
         1.1415,  0.0186, -1.8058,  0.9254, -0.3753,  1.0331, -0.6867,  0.6368,
        -0.9727,  0.9585,  1.6192,  1.4506,  0.2695, -0.2104, -0.7328,  0.1043,
         0.3488,  0.9676, -0.4657,  1.6048, -2.4801, -0.4175, -1.1955,  0.8123])

AFTER TRAINING:
tensor([ 1.7797,  1.1187, -1.5110, -1.0116, -0.0790,  1.8085,  0.6312,  0.7082,
         1.0927, -0.1153, -1.9181,  0.9900, -0.5849,  1.1335, -0.6251,  0.5459,
        -0.7826,  0.9063,  1.7495,  1.4282,  0.1152, -0.3255, -0.8483,  0.2167,
         0.4516,  1.0166, -0.4790,  1.5388, -2.3928, -0.3462, -1.0707,  0.8237])

CHANGE:
tensor([-0.1515,  0.1069, -0.0746,  0.1182,  0.0570,  0.1731, -0.0235,  0.1322,
        -0.0488, -0.1339, -0.1123,  0.0645, -0.2096,  0.1004,  0.0616, -0.0909,
         0.1900, -0.0521,  0.1303, -0.0224, -0.1543, -0.1151, -0.1155,  0.1124,
         0.1028,  0.0490, -0.0133, -0.0660,  0.0873,  0.0713,  0.1248,  0.0114])

### We'll do one controlled training step and inspect exactly what happens. Don't run a full epoch   

Recreate and load the trained model

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class TextEncoder(nn.Module):

    def __init__(self, vocab_size, embedding_dim=32, output_dim=16):
        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embedding_dim
        )

        self.projection = nn.Linear(
            embedding_dim,
            output_dim
        )

    def forward(self, token_ids):

        # [batch, tokens, 32]
        word_vectors = self.embedding(token_ids)

        # [batch, 32]
        sentence_vector = word_vectors.mean(dim=1)

        # [batch, 16]
        output = self.projection(sentence_vector)

        # Normalize to length 1
        return F.normalize(output, dim=1)


# Reconstruct model
model = TextEncoder(
    vocab_size=len(vocab),
    embedding_dim=checkpoint["embedding_dim"],
    output_dim=checkpoint["output_dim"]
)

# Load our trained weights
model.load_state_dict(checkpoint["model_state"])

model.train()

print(model)

TextEncoder(
  (embedding): Embedding(93, 32)
  (projection): Linear(in_features=32, out_features=16, bias=True)
)

In [22]:
for token, token_id in sorted(
    vocab.items(),
    key=lambda x: x[1]
):
    print(f"{token_id:3d}  {token}")

  0  <PAD>
  1  <UNK>
  2  a
  3  about
  4  access
  5  an
  6  and
  7  api
  8  apis
  9  application
 10  applications
 11  authentication
 12  aws
 13  backpropagation
 14  boot
 15  build
 16  cache
 17  caching
 18  cloud
 19  containers
 20  database
 21  deploy
 22  descent
 23  distributed
 24  do
 25  docker
 26  document
 27  does
 28  embeddings
 29  engine
 30  faster
 31  find
 32  for
 33  gradient
 34  how
 35  i
 36  improve
 37  in
 38  indexes
 39  java
 40  learn
 41  learning
 42  logs
 43  machine
 44  make
 45  metrics
 46  microservices
 47  model
 48  monitor
 49  my
 50  network
 51  neural
 52  oauth
 53  observe
 54  on
 55  optimize
 56  package
 57  performance
 58  protect
 59  queries
 60  query
 61  reduce
 62  response
 63  rest
 64  retrieval
 65  run
 66  search
 67  secure
 68  security
 69  semantic
 70  services
 71  similar
 72  software
 73  speed
 74  spring
 75  sql
 76  store
 77  text
 78  the
 79  time
 80  to
 81  tokens
 82  traces
 83  tracing
 84  train
 85  training
 86  up
 87  use
 88  using
 89  vector
 90  vectors
 91  with
 92  work

In [24]:
words_to_check = [
    "neural",
    "network",
    "networks",
    "training",
    "learn",
    "backpropagation",
    "spring",
    "boot",
    "aws",
    "transform"
]

for word in words_to_check:
    print(
        f"{word:20s}",
        vocab.get(word, "NOT IN VOCAB")
    )

neural               51
network              50
networks             NOT IN VOCAB
training             85
learn                40
backpropagation      13
spring               74
boot                 14
aws                  12
transform            NOT IN VOCAB

Define our controlled training example

In [25]:
query_text = "neural network training"

positive_text = "neural network learn backpropagation"

negative_text = "spring boot aws"

In [26]:
def tokenize(text):
    return text.lower().split()

In [27]:
print("QUERY:")
print(tokenize(query_text))

print("\nPOSITIVE:")
print(tokenize(positive_text))

print("\nNEGATIVE:")
print(tokenize(negative_text))

QUERY:
['neural', 'network', 'training']

POSITIVE:
['neural', 'network', 'learn', 'backpropagation']

NEGATIVE:
['spring', 'boot', 'aws']

# For this controlled experiment, I actually want to fail loudly if a word doesn't exist instead of silently mapping it to <UNK>.

In [28]:
def to_ids(text):

    tokens = tokenize(text)

    ids = []

    for token in tokens:

        if token not in vocab:
            raise ValueError(
                f"Token '{token}' is not in vocabulary"
            )

        ids.append(vocab[token])

    return tokens, ids

In [29]:
q_tokens, q_ids = to_ids(query_text)
p_tokens, p_ids = to_ids(positive_text)
n_tokens, n_ids = to_ids(negative_text)

print("QUERY")
print(q_tokens)
print(q_ids)

print("\nPOSITIVE")
print(p_tokens)
print(p_ids)

print("\nNEGATIVE")
print(n_tokens)
print(n_ids)

QUERY
['neural', 'network', 'training']
[51, 50, 85]

POSITIVE
['neural', 'network', 'learn', 'backpropagation']
[51, 50, 40, 13]

NEGATIVE
['spring', 'boot', 'aws']
[74, 14, 12]

Convert IDs into tensors

In [ ]:
q_tensor = torch.tensor([q_ids])
p_tensor = torch.tensor([p_ids])
n_tensor = torch.tensor([n_ids])

print("Query tensor:", q_tensor)
print("Shape:", q_tensor.shape)

print("\nPositive tensor:", p_tensor)
print("Shape:", p_tensor.shape)
print("dim weights: ", p_tensor)


print("\nNegative tensor:", n_tensor)
print("Shape:", n_tensor.shape)

Query tensor: tensor([[51, 50, 85]])
Shape: torch.Size([1, 3])

Positive tensor: tensor([[51, 50, 40, 13]])
Shape: torch.Size([1, 4])

Negative tensor: tensor([[74, 14, 12]])
Shape: torch.Size([1, 3])

In [ ]:

# So need to take snapshot and frozen copies of all 3,504 parameters before our experiment.

embedding_before = (
    model.embedding.weight
    .detach()
    .clone()
)



print(embedding_before.shape)


projection_before = (
    model.projection.weight
    .detach()
    .clone()
)

print(projection_before.shape)

bias_before = (
    model.projection.bias
    .detach()
    .clone()
)

print(bias_before.shape)

torch.Size([93, 32])
torch.Size([16, 32])
torch.Size([16])

In [51]:
#### let's see model parameters
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-1.3847, -0.8712, -0.2234,  ...,  1.8446, -1.1845,  1.3835],
        [ 1.4122,  0.7336,  2.2255,  ..., -0.7492,  1.3516,  0.5532],
        ...,
        [-0.5463, -0.6607,  0.2517,  ..., -0.4410,  1.0555, -1.3477],
        [ 0.4723, -0.0795, -0.1661,  ..., -1.1575,  0.0462, -0.3146],
        [ 0.8535, -0.0585,  0.7543,  ...,  0.3706,  0.1984,  0.2184]],
       requires_grad=True)
Parameter containing:
tensor([[-0.0552, -0.1633,  0.1319,  0.1599,  0.0228,  0.0574, -0.0739,  0.0343,
         -0.2089,  0.1686, -0.0109, -0.2053,  0.1009, -0.0133, -0.2326, -0.0739,
         -0.0716,  0.0324,  0.0504, -0.0366, -0.1892,  0.2162, -0.0940,  0.0485,
          0.0446,  0.0818, -0.0184, -0.0829,  0.1041, -0.1501, -0.1356,  0.0066],
        [ 0.0164, -0.0352, -0.0234,  0.0034, -0.0363,  0.1689, -0.0331, -0.0672,
          0.1146,  0.2569,  0.0576, -0.0458, -0.2000,  0.0231,  0.1940, -0.1813,
          0.1760, -0.1764,  0.0234,  0.1792, -0.0340, -0.1864,  0.0828,  0.1561,
          0.0379,  0.0004,  0.1797,  0.0263, -0.1508,  0.0419,  0.0478, -0.1945],
        [ 0.0015, -0.2025, -0.1734,  0.1165, -0.2078,  0.0071,  0.0140,  0.1710,
         -0.1555, -0.2101,  0.1090,  0.1432,  0.2985,  0.0583, -0.0254,  0.1438,
         -0.0753, -0.0375, -0.1863,  0.1612,  0.1516,  0.2897, -0.2977, -0.0745,
         -0.1346, -0.0415,  0.0143, -0.1878,  0.1663,  0.0148, -0.1019, -0.0524],
        [ 0.0387,  0.1040, -0.1258, -0.2026, -0.0352,  0.1756,  0.0817,  0.0171,
         -0.0108,  0.0575, -0.1383, -0.2533, -0.0496, -0.0631, -0.0629,  0.1903,
         -0.0806,  0.0750, -0.0112, -0.0509, -0.1258,  0.0830,  0.1925,  0.1170,
         -0.0345,  0.1131, -0.2551, -0.0102,  0.1107, -0.1115, -0.2217, -0.2173],
        [ 0.1441,  0.0610, -0.1824,  0.0718,  0.0337, -0.0017,  0.0108, -0.0390,
          0.0856,  0.1330,  0.0040,  0.0157, -0.2443,  0.0282, -0.0461, -0.0569,
          0.0723, -0.0791,  0.1499,  0.1047, -0.0125, -0.1803,  0.0599,  0.0302,
          0.1157,  0.2316,  0.0736,  0.1404,  0.1179, -0.0434, -0.1559,  0.0246],
        [ 0.1139, -0.0646,  0.0763,  0.1245, -0.1243, -0.2284,  0.0014, -0.0271,
         -0.0637,  0.0268,  0.2830, -0.2339,  0.1222, -0.0778, -0.1353,  0.1819,
         -0.1285,  0.0881,  0.0040,  0.2712, -0.0102,  0.0052,  0.2384, -0.0449,
          0.0235,  0.0597, -0.1610, -0.0065, -0.0149,  0.2774, -0.1586,  0.0619],
        [ 0.1804, -0.1689,  0.2456,  0.2497,  0.0077, -0.2738,  0.1445,  0.0593,
         -0.0217, -0.2219,  0.1801,  0.0272, -0.1648, -0.0534,  0.0121, -0.1598,
          0.0434, -0.0472, -0.0197, -0.0931, -0.1351, -0.1711, -0.0025,  0.2328,
         -0.2280,  0.1785, -0.1828,  0.0320,  0.0707, -0.0117,  0.0508, -0.1136],
        [-0.1480,  0.0116,  0.0651,  0.1231, -0.2654,  0.0803,  0.0901,  0.3034,
          0.1025, -0.1752,  0.1890,  0.0793, -0.1983,  0.0524, -0.0054,  0.2922,
          0.2090,  0.0830, -0.1306, -0.1555, -0.1581,  0.0231,  0.0021, -0.0054,
         -0.1455, -0.2250, -0.1089,  0.0885, -0.0515,  0.1799,  0.0577, -0.0559],
        [ 0.0469,  0.0339, -0.0836,  0.0542,  0.1428,  0.2236, -0.0581,  0.0235,
         -0.1991, -0.1161, -0.1327,  0.1108,  0.2534, -0.0382, -0.1856, -0.1812,
          0.0389,  0.0363,  0.1617, -0.1918, -0.1907,  0.1803, -0.1470, -0.0207,
          0.0266, -0.0627, -0.1634, -0.1608,  0.0324, -0.1753,  0.1103, -0.0862],
        [-0.0134, -0.1469,  0.1700,  0.1386, -0.0527,  0.2426, -0.2762,  0.1678,
          0.0246,  0.0433, -0.2389, -0.1772, -0.1306,  0.1291, -0.1820,  0.0664,
         -0.1834,  0.0644,  0.1052,  0.2292, -0.1384,  0.2227,  0.1025,  0.1438,
         -0.0168,  0.1386, -0.1345,  0.0480,  0.1651,  0.0111, -0.0875,  0.1797],
        [-0.0702, -0.0132, -0.0895, -0.2673,  0.0372, -0.1797,  0.1193, -0.2211,
         -0.1829, -0.1085, -0.2359,  0.0914,  0.0986, -0.0046,  0.1720, -0.0635,
          0.0226, -0.0429,  0.0081, -0.1918,  0.1577, -0.0009, -0.0310, -0.0038,
          0.1590, -0.0024, -0.1171, -0.1054, -0.0743,  0.0521,  0.0370, -0.0810],
        [ 0.0504, -0.2064,  0.2344, -0.0278,  0.0573, -0.0908,  0.0914,  0.0061,
          0.1239, -0.2052,  0.0042,  0.1272, -0.0779,  0.0872,  0.2355, -0.1775,
         -0.0032,  0.0107,  0.0140, -0.2322, -0.2034, -0.2159,  0.2794,  0.1307,
         -0.0331, -0.0467, -0.2242,  0.0154,  0.0810, -0.1619,  0.0503, -0.1848],
        [ 0.0384, -0.0162,  0.2528, -0.0563, -0.1476,  0.0710, -0.0322, -0.0986,
          0.0556,  0.0684, -0.0553, -0.0422, -0.2193,  0.0241,  0.0183,  0.0326,
          0.0084,  0.0416,  0.0407, -0.1290,  0.0543, -0.1630,  0.0602,  0.2369,
         -0.2726, -0.1256,  0.0053, -0.0206, -0.1188,  0.0105,  0.0731,  0.1231],
        [ 0.0927, -0.1181,  0.1102,  0.1281,  0.1147,  0.0526,  0.1577,  0.0873,
          0.0171, -0.1985,  0.1783, -0.0468,  0.0422, -0.0316, -0.0087, -0.0135,
          0.0425, -0.0240, -0.0570,  0.2623, -0.2504, -0.2187,  0.0259, -0.1226,
         -0.0552,  0.0037, -0.1000,  0.0305,  0.0737,  0.0467, -0.0210, -0.1362],
        [ 0.0851, -0.2966,  0.2798, -0.0885,  0.1074, -0.2472,  0.0117, -0.2633,
         -0.0528,  0.1977,  0.1381,  0.0195,  0.2667, -0.0094, -0.0115,  0.0541,
         -0.1573, -0.1475, -0.2568,  0.0883,  0.1869,  0.2432,  0.0979, -0.1321,
         -0.0923, -0.1465,  0.1300, -0.1223,  0.0355, -0.1236, -0.1610, -0.0164],
        [ 0.0536,  0.0227, -0.1886, -0.0339, -0.0572,  0.1642,  0.0023,  0.2345,
          0.2575, -0.1946, -0.1381,  0.0546, -0.0890,  0.0169,  0.0315,  0.0795,
          0.0420,  0.0718,  0.0499, -0.0355, -0.2735,  0.1465, -0.3364, -0.1215,
          0.2485, -0.0280,  0.0649, -0.0446,  0.0755, -0.0662,  0.0623, -0.0817]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0464, -0.0405, -0.1042, -0.0282,  0.1398, -0.0336,  0.0729, -0.0870,
        -0.0312, -0.0338, -0.1554,  0.0621, -0.1188,  0.0178, -0.1588,  0.0968],
       requires_grad=True)

Create the optimizer

Let's use simple SGD because it makes the mathematics easier to understand than Adam.

###  Now let's create optimizer. below code says " SGD you are responsible to update these model parameters during training"

In [52]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

#### Now clear any old gradients:

In [53]:
optimizer.zero_grad()

In [54]:
q_vector = model(q_tensor)
p_vector = model(p_tensor)
n_vector = model(n_tensor)

print("QUERY VECTOR:")
print(q_vector)
print(q_vector.shape)

print("\nPOSITIVE VECTOR:")
print(p_vector)

print("\nNEGATIVE VECTOR:")
print(n_vector)

QUERY VECTOR:
tensor([[ 0.2740, -0.2991,  0.2907,  0.4889, -0.0888,  0.2794,  0.1445,  0.1956,
          0.1807,  0.3596, -0.1986,  0.1413, -0.0628,  0.3460,  0.0467, -0.1403]],
       grad_fn=<DivBackward0>)
torch.Size([1, 16])

POSITIVE VECTOR:
tensor([[ 1.3478e-01, -2.8718e-01,  2.0198e-01,  2.7932e-01, -4.4134e-02,
          4.7266e-01,  3.7413e-01,  2.3114e-01, -4.5479e-05,  2.3535e-01,
         -1.2568e-01,  2.4360e-01, -7.6428e-02,  4.5410e-01, -5.0887e-02,
         -1.2894e-01]], grad_fn=<DivBackward0>)

NEGATIVE VECTOR:
tensor([[-0.1786, -0.4805,  0.4929, -0.3252, -0.1167,  0.0550, -0.0482,  0.1965,
          0.0614, -0.2906,  0.0480, -0.2393, -0.3278, -0.0095, -0.0022,  0.2749]],
       grad_fn=<DivBackward0>)

#### tokens
  ↓
#### 32-D embeddings
  ↓
#### average
  ↓
#### 32-D sentence representation
  ↓
#### projection
  ↓
#### 16-D representation
  ↓
#### normalize


#### No learning has happened yet.

Calculate similarity

In [55]:
positive_similarity = F.cosine_similarity(
    q_vector,
    p_vector
)

negative_similarity = F.cosine_similarity(
    q_vector,
    n_vector
)

print(
    "Positive similarity:",
    positive_similarity.item()
)

print(
    "Negative similarity:",
    negative_similarity.item()
)

Positive similarity: 0.8749660849571228
Negative similarity: -0.02182886004447937

In [56]:
loss = F.softplus(
    negative_similarity -
    positive_similarity
).mean()

print("LOSS:", loss.item())

LOSS: 0.34208136796951294

### Verify that NOTHING has changed yet. We performed the entire forward pass and calculated loss.

In [38]:
difference = (
    model.embedding.weight.detach()
    - embedding_before
)

print(
    "Largest weight change BEFORE backward:",
    difference.abs().max().item()
)

Largest weight change BEFORE backward: 0.0

### Now perform BACKPROPAGATION. And with this PyTorch will now calculated gradients.

In [61]:
loss.backward()
print(
    model.embedding.weight.grad
)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

# embedding.weight

WEIGHTS
93 × 32

GRADIENTS
93 × 32

# For every embedding weight PyTorch has a corresponding gradient slot. Optimizer uses thiese gradient to update the weight so that loss can be reduced

In [40]:
token = "neural"
token_id = vocab[token]

print("Token:", token)
print("ID:", token_id)

print("\nWEIGHTS:")
print(model.embedding.weight[token_id])

print("\nGRADIENT:")
print(model.embedding.weight.grad[token_id])

Token: neural
ID: 51

WEIGHTS:
tensor([-0.8287, -0.7873,  0.3435, -0.3625, -0.0855, -0.0741,  1.6253,  1.1130,
        -0.2780, -1.3326,  0.7128, -0.2497,  0.2439,  1.1499, -0.8190,  1.0209,
         0.3290,  0.1647, -0.0034, -0.1073, -1.5734, -0.4588,  0.8014, -0.1305,
        -1.3829,  0.3357, -1.2171,  0.6354,  0.1020,  0.4593, -1.6589, -0.3244],
       grad_fn=<SelectBackward0>)

GRADIENT:
tensor([-3.5056e-03,  2.5657e-03, -1.2305e-02,  6.6345e-07, -2.7321e-03,
        -3.9419e-03,  2.0586e-03,  5.4495e-03, -2.7943e-03, -1.0485e-02,
         2.5532e-03,  1.1084e-02,  1.3230e-02, -3.7727e-04, -7.8041e-04,
         6.3697e-03,  1.0124e-03,  1.0461e-03, -5.5666e-03, -1.6297e-03,
         7.2103e-03,  1.1267e-02, -1.7803e-02, -1.3472e-02,  4.1421e-03,
        -6.2579e-03,  5.8287e-03, -4.8954e-03,  6.7061e-04,  2.8770e-03,
         3.1984e-03,  2.6794e-03])

In [60]:
difference_after_backward = (
    model.embedding.weight.detach()
    - embedding_before
)

print(
    "Largest weight change AFTER backward:",
    difference_after_backward.abs().max().item()
)

Largest weight change AFTER backward: 0.00019347667694091797

## Now change the weights

This is the line that actually changes them:

In [62]:
optimizer.step()

In [43]:
difference_after_step = (
    model.embedding.weight.detach()
    - embedding_before
)

print(
    "Largest weight change AFTER optimizer.step():",
    difference_after_step.abs().max().item()
)

Largest weight change AFTER optimizer.step(): 0.00019347667694091797

## Look at "neural" BEFORE vs AFTER

In [44]:
token = "neural"
token_id = vocab[token]

before = embedding_before[token_id]
after = model.embedding.weight[token_id].detach()

change = after - before

print("TOKEN:", token)

print("\nBEFORE:")
print(before)

print("\nGRADIENT:")
print(model.embedding.weight.grad[token_id])

print("\nAFTER:")
print(after)

print("\nCHANGE:")
print(change)

TOKEN: neural

BEFORE:
tensor([-0.8287, -0.7873,  0.3435, -0.3625, -0.0855, -0.0741,  1.6253,  1.1130,
        -0.2780, -1.3326,  0.7128, -0.2497,  0.2439,  1.1499, -0.8190,  1.0209,
         0.3290,  0.1647, -0.0034, -0.1073, -1.5734, -0.4588,  0.8014, -0.1305,
        -1.3829,  0.3357, -1.2171,  0.6354,  0.1020,  0.4593, -1.6589, -0.3244])

GRADIENT:
tensor([-3.5056e-03,  2.5657e-03, -1.2305e-02,  6.6345e-07, -2.7321e-03,
        -3.9419e-03,  2.0586e-03,  5.4495e-03, -2.7943e-03, -1.0485e-02,
         2.5532e-03,  1.1084e-02,  1.3230e-02, -3.7727e-04, -7.8041e-04,
         6.3697e-03,  1.0124e-03,  1.0461e-03, -5.5666e-03, -1.6297e-03,
         7.2103e-03,  1.1267e-02, -1.7803e-02, -1.3472e-02,  4.1421e-03,
        -6.2579e-03,  5.8287e-03, -4.8954e-03,  6.7061e-04,  2.8770e-03,
         3.1984e-03,  2.6794e-03])

AFTER:
tensor([-0.8287, -0.7874,  0.3436, -0.3625, -0.0854, -0.0741,  1.6253,  1.1130,
        -0.2780, -1.3325,  0.7128, -0.2498,  0.2438,  1.1499, -0.8190,  1.0209,
         0.3290,  0.1647, -0.0033, -0.1073, -1.5734, -0.4589,  0.8016, -0.1303,
        -1.3830,  0.3358, -1.2172,  0.6354,  0.1020,  0.4593, -1.6589, -0.3245])

CHANGE:
tensor([ 3.5048e-05, -2.5630e-05,  1.2305e-04,  0.0000e+00,  2.7321e-05,
         3.9421e-05, -2.0623e-05, -5.4479e-05,  2.7955e-05,  1.0490e-04,
        -2.5511e-05, -1.1083e-04, -1.3231e-04,  3.8147e-06,  7.8082e-06,
        -6.3658e-05, -1.0133e-05, -1.0461e-05,  5.5666e-05,  1.6294e-05,
        -7.2122e-05, -1.1268e-04,  1.7804e-04,  1.3472e-04, -4.1366e-05,
         6.2585e-05, -5.8293e-05,  4.8935e-05, -6.7055e-06, -2.8759e-05,
        -3.1948e-05, -2.6792e-05])

## Prove the SGD equation .Because we're using: lr = 0.01. SGD performs:

## Wnew ​= Wold ​− 0.01×gradient

## Let's verify dimension 0 manually.

Expected and Actual should match apart from tiny floating-point differences.

That gives you direct experimental proof of:

weightnew = weightold − learningRate × gradient

In [45]:
token = "neural"
token_id = vocab[token]

old_value = embedding_before[token_id][0]

gradient = model.embedding.weight.grad[token_id][0]

expected_new_value = (
    old_value - 0.01 * gradient
)

actual_new_value = (
    model.embedding.weight[token_id][0].detach()
)

print("Old value:")
print(old_value.item())

print("\nGradient:")
print(gradient.item())

print("\nExpected:")
print(expected_new_value.item())

print("\nActual:")
print(actual_new_value.item())

Old value:
-0.8287467956542969

Gradient:
-0.00350556755438447

Expected:
-0.828711748123169

Actual:
-0.828711748123169

## Now inspect ALL tokens that changed

In [47]:
embedding_after = (
    model.embedding.weight
    .detach()
    .clone()
)

change = embedding_after - embedding_before

change_per_token = torch.linalg.vector_norm(
    change,
    dim=1
)

results = []

for token, token_id in vocab.items():

    results.append({
        "token": token,
        "token_id": token_id,
        "change": change_per_token[token_id].item()
    })

import pandas as pd

pd.set_option("display.max_rows", None)


change_df = pd.DataFrame(results)

change_df = change_df.sort_values(
    "change",
    ascending=False
)

display(change_df)

              token  token_id    change
85         training        85  0.000444
12              aws        12  0.000402
74           spring        74  0.000402
14             boot        14  0.000402
50          network        50  0.000393
51           neural        51  0.000393
13  backpropagation        13  0.000143
40            learn        40  0.000143
56          package        56  0.000000
61           reduce        61  0.000000
67           secure        67  0.000000
66           search        66  0.000000
52            oauth        52  0.000000
65              run        65  0.000000
64        retrieval        64  0.000000
63             rest        63  0.000000
62         response        62  0.000000
60            query        60  0.000000
55         optimize        55  0.000000
59          queries        59  0.000000
53          observe        53  0.000000
69         semantic        69  0.000000
54               on        54  0.000000
58          protect        58  0.000000
57      performance        57  0.000000
68         security        68  0.000000
0             <PAD>         0  0.000000
70         services        70  0.000000
82           traces        82  0.000000
91             with        91  0.000000
90          vectors        90  0.000000
89           vector        89  0.000000
88            using        88  0.000000
87              use        87  0.000000
86               up        86  0.000000
84            train        84  0.000000
83          tracing        83  0.000000
81           tokens        81  0.000000
71          similar        71  0.000000
80               to        80  0.000000
79             time        79  0.000000
78              the        78  0.000000
77             text        77  0.000000
76            store        76  0.000000
75              sql        75  0.000000
73            speed        73  0.000000
49               my        49  0.000000
72         software        72  0.000000
46    microservices        46  0.000000
48          monitor        48  0.000000
47            model        47  0.000000
23      distributed        23  0.000000
22          descent        22  0.000000
21           deploy        21  0.000000
20         database        20  0.000000
19       containers        19  0.000000
18            cloud        18  0.000000
17          caching        17  0.000000
16            cache        16  0.000000
15            build        15  0.000000
11   authentication        11  0.000000
10     applications        10  0.000000
9       application         9  0.000000
8              apis         8  0.000000
7               api         7  0.000000
6               and         6  0.000000
5                an         5  0.000000
4            access         4  0.000000
3             about         3  0.000000
2                 a         2  0.000000
24               do        24  0.000000
25           docker        25  0.000000
26         document        26  0.000000
37               in        37  0.000000
1             <UNK>         1  0.000000
45          metrics        45  0.000000
44             make        44  0.000000
43          machine        43  0.000000
42             logs        42  0.000000
41         learning        41  0.000000
39             java        39  0.000000
38          indexes        38  0.000000
36          improve        36  0.000000
27             does        27  0.000000
35                i        35  0.000000
34              how        34  0.000000
33         gradient        33  0.000000
32              for        32  0.000000
31             find        31  0.000000
30           faster        30  0.000000
29           engine        29  0.000000
28       embeddings        28  0.000000
92             work        92  0.000000

### Now inspect ALL tokens that changed

In [48]:
embedding_after = (
    model.embedding.weight
    .detach()
    .clone()
)

change = embedding_after - embedding_before

change_per_token = torch.linalg.vector_norm(
    change,
    dim=1
)

results = []

for token, token_id in vocab.items():

    results.append({
        "token": token,
        "token_id": token_id,
        "change": change_per_token[token_id].item()
    })

import pandas as pd

change_df = pd.DataFrame(results)

change_df = change_df.sort_values(
    "change",
    ascending=False
)

display(change_df)

              token  token_id    change
85         training        85  0.000444
12              aws        12  0.000402
74           spring        74  0.000402
14             boot        14  0.000402
50          network        50  0.000393
51           neural        51  0.000393
13  backpropagation        13  0.000143
40            learn        40  0.000143
56          package        56  0.000000
61           reduce        61  0.000000
67           secure        67  0.000000
66           search        66  0.000000
52            oauth        52  0.000000
65              run        65  0.000000
64        retrieval        64  0.000000
63             rest        63  0.000000
62         response        62  0.000000
60            query        60  0.000000
55         optimize        55  0.000000
59          queries        59  0.000000
53          observe        53  0.000000
69         semantic        69  0.000000
54               on        54  0.000000
58          protect        58  0.000000
57      performance        57  0.000000
68         security        68  0.000000
0             <PAD>         0  0.000000
70         services        70  0.000000
82           traces        82  0.000000
91             with        91  0.000000
90          vectors        90  0.000000
89           vector        89  0.000000
88            using        88  0.000000
87              use        87  0.000000
86               up        86  0.000000
84            train        84  0.000000
83          tracing        83  0.000000
81           tokens        81  0.000000
71          similar        71  0.000000
80               to        80  0.000000
79             time        79  0.000000
78              the        78  0.000000
77             text        77  0.000000
76            store        76  0.000000
75              sql        75  0.000000
73            speed        73  0.000000
49               my        49  0.000000
72         software        72  0.000000
46    microservices        46  0.000000
48          monitor        48  0.000000
47            model        47  0.000000
23      distributed        23  0.000000
22          descent        22  0.000000
21           deploy        21  0.000000
20         database        20  0.000000
19       containers        19  0.000000
18            cloud        18  0.000000
17          caching        17  0.000000
16            cache        16  0.000000
15            build        15  0.000000
11   authentication        11  0.000000
10     applications        10  0.000000
9       application         9  0.000000
8              apis         8  0.000000
7               api         7  0.000000
6               and         6  0.000000
5                an         5  0.000000
4            access         4  0.000000
3             about         3  0.000000
2                 a         2  0.000000
24               do        24  0.000000
25           docker        25  0.000000
26         document        26  0.000000
37               in        37  0.000000
1             <UNK>         1  0.000000
45          metrics        45  0.000000
44             make        44  0.000000
43          machine        43  0.000000
42             logs        42  0.000000
41         learning        41  0.000000
39             java        39  0.000000
38          indexes        38  0.000000
36          improve        36  0.000000
27             does        27  0.000000
35                i        35  0.000000
34              how        34  0.000000
33         gradient        33  0.000000
32              for        32  0.000000
31             find        31  0.000000
30           faster        30  0.000000
29           engine        29  0.000000
28       embeddings        28  0.000000
92             work        92  0.000000

#### And one final experiment before we stop

#### Don't run another optimizer step.

#### Use the same query/documents again, but only forward-pass them:

In [63]:
with torch.no_grad():

    q_after = model(q_tensor)
    p_after = model(p_tensor)
    n_after = model(n_tensor)

    pos_after = F.cosine_similarity(
        q_after,
        p_after
    ).item()

    neg_after = F.cosine_similarity(
        q_after,
        n_after
    ).item()


print("BEFORE TRAINING STEP")
print("Positive:", positive_similarity.item())
print("Negative:", negative_similarity.item())

print("\nAFTER ONE TRAINING STEP")
print("Positive:", pos_after)
print("Negative:", neg_after)

BEFORE TRAINING STEP
Positive: 0.8749660849571228
Negative: -0.02182886004447937

AFTER ONE TRAINING STEP
Positive: 0.8755993247032166
Negative: -0.03360237181186676

###  weights are what ultimately change during training. The gradient tells the optimizer how each weight should change.
#### A useful mental model is:
#### Weight = what the model currently knows.
#### Gradient = the direction and strength of the correction needed.

### Let's create a serach utility

In [68]:
# ============================================================
# SEMANTIC SEARCH UTILITY — TOP 3 RESULTS
# ============================================================

import sys
import json
from pathlib import Path

import torch
import torch.nn.functional as F


# ============================================================
# 1. PROJECT SETUP
# ============================================================

PROJECT_ROOT = Path("..").resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.model import TextEncoder


MODEL_PATH = PROJECT_ROOT / "models" / "text_encoder.pt"
DATA_PATH = PROJECT_ROOT / "data" / "training_pairs.json"


# ============================================================
# 2. LOAD TRAINED MODEL CHECKPOINT
# ============================================================

checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
    weights_only=True
)

vocab = checkpoint["vocab"]


# ============================================================
# 3. RECREATE MODEL ARCHITECTURE
# ============================================================

model = TextEncoder(
    vocab_size=len(vocab),
    embedding_dim=checkpoint["embedding_dim"],
    output_dim=checkpoint["output_dim"]
)


# Load trained weights
model.load_state_dict(
    checkpoint["model_state"]
)


# Put model into inference mode
model.eval()


print("Model loaded successfully")
print("Vocabulary size :", len(vocab))
print("Embedding dim   :", checkpoint["embedding_dim"])
print("Output dim      :", checkpoint["output_dim"])


# ============================================================
# 4. LOAD DOCUMENTS
# ============================================================

with open(
    DATA_PATH,
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)


documents = data["documents"]


print("\nDocuments available for search:", len(documents))


# ============================================================
# 5. TEXT -> TOKEN TENSOR
# ============================================================

def text_to_tensor(text):

    tokens = tokenize(text)

    # Try to find UNK token
    unk_id = None

    if "<UNK>" in vocab:
        unk_id = vocab["<UNK>"]

    elif "<unk>" in vocab:
        unk_id = vocab["<unk>"]


    token_ids = []


    for token in tokens:

        if token in vocab:

            token_ids.append(
                vocab[token]
            )

        elif unk_id is not None:

            token_ids.append(
                unk_id
            )

        else:

            # Ignore words that are completely unknown
            print(
                f"Warning: ignoring unknown token: '{token}'"
            )


    # Nothing usable in the query
    if len(token_ids) == 0:
        return None


    return torch.tensor(
        [token_ids],
        dtype=torch.long
    )


# ============================================================
# 6. TEXT -> 16-D VECTOR
# ============================================================

def encode_text(text):

    tensor = text_to_tensor(text)

    if tensor is None:
        return None


    with torch.no_grad():

        vector = model(tensor)


    return vector


# ============================================================
# 7. PRECOMPUTE DOCUMENT VECTORS
# ============================================================

document_vectors = []


for document in documents:

    document_id = document["id"]

    document_text = document["text"]


    vector = encode_text(
        document_text
    )


    if vector is not None:

        document_vectors.append({

            "id": document_id,

            "text": document_text,

            "vector": vector
        })


print(
    "Documents successfully encoded:",
    len(document_vectors)
)


# ============================================================
# 8. SEARCH FUNCTION
# ============================================================

def search(question, top_k=3):

    # --------------------------------------------------------
    # Encode user question
    # --------------------------------------------------------

    query_vector = encode_text(
        question
    )


    if query_vector is None:

        print(
            "\nCould not encode query."
        )

        return []


    # --------------------------------------------------------
    # Display query internals
    # --------------------------------------------------------

    query_tokens = tokenize(
        question
    )


    print("\nQUERY TOKENS:")
    print(query_tokens)


    print("\nTOKEN IDs:")


    for token in query_tokens:

        if token in vocab:

            print(
                f"{token:20s} -> {vocab[token]}"
            )

        else:

            print(
                f"{token:20s} -> OOV"
            )


    print("\nFINAL 16-D QUERY VECTOR:")

    print(
        query_vector.squeeze(0)
    )


    # --------------------------------------------------------
    # Calculate similarity against every document
    # --------------------------------------------------------

    results = []


    for document in document_vectors:

        similarity = F.cosine_similarity(

            query_vector,

            document["vector"]

        ).item()


        results.append({

            "id": document["id"],

            "text": document["text"],

            "similarity": similarity
        })


    # --------------------------------------------------------
    # Sort highest similarity first
    # --------------------------------------------------------

    results.sort(

        key=lambda x: x["similarity"],

        reverse=True
    )


    return results[:top_k]


# ============================================================
# 9. INTERACTIVE SEARCH
# ============================================================

question = input(
    "\nEnter your question: "
)


results = search(
    question,
    top_k=3
)


# ============================================================
# 10. DISPLAY TOP 3 RESULTS
# ============================================================

print("\n")
print("=" * 80)

print(
    "TOP 3 SEMANTIC SEARCH RESULTS"
)

print("=" * 80)


if not results:

    print(
        "No results found."
    )

else:

    for rank, result in enumerate(
        results,
        start=1
    ):

        print(
            f"\nRank #{rank}"
        )

        print(
            f"Document ID : "
            f"{result['id']}"
        )

        print(
            f"Similarity  : "
            f"{result['similarity']:.6f}"
        )

        print(
            f"Answer      : "
            f"{result['text']}"
        )

        print(
            "-" * 80
        )

Model loaded successfully
Vocabulary size : 93
Embedding dim   : 32
Output dim      : 16

Documents available for search: 8
Documents successfully encoded: 8

QUERY TOKENS:
['make', 'my', 'application', 'faster', 'with', 'a', 'cache']

TOKEN IDs:
make                 -> 44
my                   -> 49
application          -> 9
faster               -> 30
with                 -> 91
a                    -> 2
cache                -> 16

FINAL 16-D QUERY VECTOR:
tensor([-0.1243,  0.2496, -0.0856, -0.1492, -0.0572, -0.5439,  0.1040,  0.0941,
         0.2888, -0.4178,  0.0501,  0.2702, -0.0473, -0.0258, -0.2560,  0.4147])


================================================================================
TOP 3 SEMANTIC SEARCH RESULTS
================================================================================

Rank #1
Document ID : d4
Similarity  : 0.902401
Answer      : Improve application response time using caching
--------------------------------------------------------------------------------

Rank #2
Document ID : d1
Similarity  : 0.021093
Answer      : Deploy a Spring Boot application to AWS using containers
--------------------------------------------------------------------------------

Rank #3
Document ID : d8
Similarity  : 0.008289
Answer      : Optimize database queries using indexes
--------------------------------------------------------------------------------